services:
  postgresql:
    image: postgres:latest
    container_name: ataccotheque-postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - ataccotheque-network

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: ataccotheque-meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - ataccotheque-network

  backend:
    build:
      context: ./app/server
      dockerfile: Dockerfile
    container_name: ataccotheque-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?schema=public
      MEILI_HOST: http://meilisearch:770
      MEILI_ENV: production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      JWT_SECRET: ${JWT_SECRET}
      API_ENDPOINT: /api
      CORS_ORIGIN: http://localhost:8099
      WEBAUTHN_RP_ID: ${WEBAUTHN_RP_ID}
      WEBAUTHN_ORIGIN: ${WEBAUTHN_ORIGIN}
    depends_on:
      postgresql:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    volumes:
      - ../files:/app/files
    command: >
      sh -c "bunx prisma migrate deploy &&
             bunx prisma db seed &&
             bun run start"
    networks:
      - ataccotheque-network

  frontend:
    build:
      context: ./app/client
      dockerfile: Dockerfile
      args:
        VITE_API_ENDPOINT: /api
        VITE_MEILI_HOST: ${VITE_MEILI_HOST}
        VITE_MEILI_API_KEY: ${VITE_MEILI_API_KEY}
    container_name: ataccotheque-frontend
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ../files:/app/files
    command: >
      sh -c "bunx prisma migrate deploy &&
             bunx prisma db seed &&
             bun run start"
    networks:
      - ataccotheque-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        VITE_API_ENDPOINT: /api
        VITE_MEILI_API_KEY: ${VITE_MEILI_API_KEY}
    ports:
      - "8099:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ../files:/app/files:ro
    networks:
      - ataccotheque-network

volumes:
  meilisearch_data:
  postgresql_data:

networks:
  ataccotheque-network:
    driver: bridge
