FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig.json ./
COPY prisma ./prisma

RUN bun install

RUN bunx prisma generate

RUN mkdir -p /app/files && chown -R bun:bun /app
USER bun

EXPOSE 3000

CMD ["bun", "run", "dev"]
