FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lockb ./
COPY tsconfig.json ./
COPY prisma ./prisma

RUN bun install

# Générer le client Prisma
RUN bunx prisma generate

COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"]
